import html.*

fun main(args: Array<String>) {
    println("Hello World!")

    // Try adding program arguments via Run/Debug configuration.
    // Learn more about running applications: https://www.jetbrains.com/help/idea/running-applications.html.
    println("Program arguments: ${args.joinToString()}")

    fun result() =
        html {
            head {
                title { +"XML encoding with Kotlin" }
            }
            body {
                h1 { +"XML encoding with Kotlin" }
                p { +"this format can be used as an alternative markup to XML" }

                // an element with attributes and text content
                a(href = "https://kotlinlang.org") { +"Kotlin" }

                //mixed content
                p {
                    +"This is some"
                    b { +"mixed" }
                    +"text. For more see the"
                    a(href = "https://kotlinlang.org") { +"Kotlin" }
                    +"project"
                }
                p { +"some text" }

                // content generated by
                p {
                    for (arg in args)
                        +arg
                }
            }
        }

    println(result())
}